blank_issues_enabled: true
contact_links:
  - name: Report a Vulnerability
    about: To report a vulnerability please contact us directly using the following email: lattigo@tuneinsight.com.
  - name: Feature Proposal/Request
    about: We do not use GitHub Issues for features proposals or requests. If you have a proposal or would like to make a request for a feature, please contact us directly using the following email: lattigo@tuneinsight.com.
