name: CI Checks
on:
  push:
jobs:
  checks:
    name: "Run staticcheck"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: Setup Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.17
    - name: Setup tools
        run: make get_tools
    - name: Run Makefile checks
        run: make static_checks

  tests:
    name: Run Go ${{ matrix.go }} tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ '1.18', '1.17', '1.16', '1.15', '1.14', '1.13' ]

    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Go
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go }}

      - uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Build
        run: go build ./...

      - name: Run Makefile checks
        run: make test
